# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.provider "virtualbox" do |v|
    v.name = "ubuntu1404-docker"
    v.memory = 2048
  end  
  
  # network configuration
  config.vm.network "public_network", bridge: "enp2s0", auto_config: false
  # manual ip
  config.vm.provision "shell",
    run: "always",
    inline: "ifconfig eth1 192.168.100.50 netmask 255.255.255.0 up"

  config.vm.provision "shell",
    run: "always",
    inline: "ifconfig eth1:0 192.168.100.60 netmask 255.255.255.0 up"

  # default router
  config.vm.provision "shell",
    run: "always",
    inline: "route add default gw 192.168.100.1"

  # delete default gw on eth0
  config.vm.provision "shell",
    run: "always",
    inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
end
