# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.provider "virtualbox" do |v|
    v.name = "ubuntu1404-magento"
    v.memory = 1024
#  config.vm.provision "file", source: "magento.conf", destination: "magento.conf"
#  config.vm.provision "file", source: "magentoinstall.sql", destination: "magentoinstall.sql"

  config.vm.provision "shell", path: "installmagento.sh"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  end  
  
  config.vm.network "public_network", bridge: "enp1s9"

end
